### ISSUE TITLE
Error with Mindwave headset and RF dongle

### ISSUE THREAD

**Issue by anber500** [BarkleyUS/mindwave-python#6]
I have the Mindset headset with the RF dongle.
I've tested with various scripts including the code snipped from your example.

The headset connects but just after that it receives the following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "F:\code\EEG_Python_learning\mindwave.py", line 73, in run
    self.parse_payload(payload)
  File "F:\code\EEG_Python_learning\mindwave.py", line 143, in parse_payload
    raw=ord(value[0])*256+ord(value[1])
IndexError: string index out of range
```

I can't seem to figure out what the correct value should be and why I'm getting this error.

This happens all the time

**Comment by anber500** [comment]
I were able to "fix" it for now.
I wrapped the code in the parse_payload() method in a try catch. It seems to have worked.

```
                if code == RAW_VALUE:
                    try:
                        raw=ord(value[0])*256+ord(value[1])
                        if (raw>=32768):
                            raw=raw-65536
                        self.headset.raw_value = raw
                        for handler in self.headset.raw_value_handlers:
                            handler(self.headset, self.headset.raw_value)
                    except IndexError:
                        continue
```

**Comment by qubodup** [comment]
Thank you very much! I got this error after 1-2 seconds of running the example and the attention/meditation values wouldn't change afterwards.

Now it has been running for a minute and the values still change!

I would like to confirm this fix solves the problem.

My system specs just in case:

```
Distro (Arch Linux        4.1.10-2-lts x86_64
Mainboard     FOXCONN A7GM-S 2.0
CPU           AMD Phenom(tm) 9550 Quad-Core Processor
              4 x 2200 MHz, 64-bit
RAM           7.8G
Video         Advanced Micro Devices, Inc. [AMD/ATI]
              Cape Verde PRO [Radeon HD 7750/8740 / R7 250E]
OpenGL        4.4.13399 Core Profile Context 15.20.1013, GLSL 4.40
GCC           gcc (GCC) 5.2.0
```
